version: "3.3"
services:
  # Spring Boot application
  backend:
    container_name: es-autocomplete-demo
    build: .
    ports:
      - "80:8080"
    depends_on:
      - elasticsearch

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
    volumes:
      - elastic_data_volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      interval: 30s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq ""status":"red""

volumes:
  elastic_data_volume: {}
